apiVersion: v1
kind: Service
metadata:
  name: {{ include "workout-planner.fullname" . }}-backend
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: {{ include "workout-planner.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ include "workout-planner.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: backend
