services:
  db:
    image: postgres:17
    container_name: fitness-db
    restart: always
    environment:
      POSTGRES_USER: fitness_user
      POSTGRES_PASSWORD: fitness_password
      POSTGRES_DB: fitness_tracker
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    container_name: fitness-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://fitness_user:fitness_password@db:5432/fitness_tracker
      - JWT_SECRET=youshallnotpass
    depends_on:
      - db

volumes:
  postgres_data:
