apiVersion: v1
kind: Secret
metadata:
  name: {{ include "workout-planner.fullname" . }}-secrets
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: {{ include "workout-planner.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  mongodb-root-username: {{ .Values.secrets.mongodbRoot.username | quote }}
  mongodb-root-password: {{ .Values.secrets.mongodbRoot.password | quote }}
