apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "workout-planner.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: {{ include "workout-planner.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
