## This is a Helm chart for deploying the Workout Planner application on Kubernetes.
## The values in this file can be overridden by providing a custom values.yaml file when installing the chart.

backend:
  enabled: false

chroma:
  enabled: true

frontend:
  enabled: false

mcp:
  enabled: false

ollama:
  enabled: false
