apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "workout-planner.fullname" . }}-mongodb-pvc
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: {{ include "workout-planner.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.mongodb.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.size }}
