apiVersion: v1
kind: Service
metadata:
  name: {{ include "workout-planner.fullname" . }}-mongodb
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: {{ include "workout-planner.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: mongodb
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "workout-planner.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: mongodb
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongodb
