apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: workout-planner-ingress
  namespace: workout-planner
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: workout-planner.local
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: svelte-frontend
                port:
                  number: 80
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: rustdb-backend
                port:
                  number: 8080
