apiVersion: v1
kind: Secret
metadata:
  name: workout-planner-secrets
  namespace: workout-planner
type: Opaque
data:
  CHROMA_API_KEY: "REPLACE_WITH_BASE64_ENCODED_VALUE"
  OLLAMA_API_KEY: "REPLACE_WITH_BASE64_ENCODED_VALUE"
  BACKEND_SECRET: "REPLACE_WITH_BASE64_ENCODED_VALUE"
