apiVersion: v1
kind: Secret
metadata:
  name: workout-planner-secrets
  namespace: workout-planner
type: Opaque
stringData:
  CHROMA_API_KEY: "{{ .Values.secrets.chromaApiKey }}"
  OLLAMA_API_KEY: "{{ .Values.secrets.ollamaApiKey }}"
  BACKEND_SECRET: "{{ .Values.secrets.backendSecret }}"